spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kinodb
    username: admin
    password: fhdw

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Alternativ "validate", falls das Schema manuell verwaltet wird

  data:
    mongodb:
      uri: mongodb://mongo:27017/kinodb
